name: ting ting
name2: hellooooheloooo



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8099/eureka/
  instance:
    hostname: localhost
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
